### ISSUE TITLE
CC BY-SA-4.0 license

### ISSUE THREAD

**Issue by MCKevmeister** [replit/ReplitLM#6]
It appears that the CC BY-SA-4.0 license is not included in the repository, which raises concerns about its licensing status. Could you please provide a link to the license or clarify where it can be found? As per my understanding, the license must be included with the code, and its absence may render the code unlicensed.

**Comment by pirroh** [comment]
Thanks for flagging this.
This repo contains exclusively code released under the Apache-2.0 license.
In the [README](https://github.com/replit/ReplitLM/blob/main/README.md) file, we provide links to download the model checkpoints and vocabulary files (hosted on the HuggingFace Hub) which are released under CC BY-SA 4.0.
Hope this clears all your concerns!
